CARFIN
#   name ixl ixu iyl iyu izl izu nxref nyref nzref
    LGR1 9   10  18   18   1   192 40    20    192   /
ENDFIN

CARFIN
#   name ixl ixu iyl iyu izl izu nxref nyref nzref
    LGR2 9   10  3   3   1   192 40    20    192   /
ENDFIN

CARFIN
#   name ixl ixu iyl iyu izl izu nxref nyref nzref
    LGR3 26  27  18  18  1   192 40    20    192   /
ENDFIN

CARFIN
#   name ixl ixu iyl iyu izl izu nxref nyref nzref
    LGR4 24  25  3   3   1   192 40    20    192   /
ENDFIN
